name: build

# Controls when the workflow will run
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  
  tests:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Build tests
      run: |
        g++ -std=c++20 -Wall -Wextra -pedantic -Werror tests/tests.cpp -I tests -I. -o tests/tests
    - name: Run tests
      run: ./tests/tests
